# Generated by Django 4.1.4 on 2024-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=70)),
                ('title', models.CharField(max_length=5000)),
                ('content', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
    ]
